# Generated by Django 4.0.2 on 2022-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewup_app', '0004_tech_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'news_startup',
            },
        ),
    ]
