# Generated by Django 4.0.2 on 2022-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewup_app', '0005_tech_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('did', models.IntegerField(db_column='did', primary_key=True, serialize=False)),
                ('dname', models.CharField(db_column='dname', max_length=50)),
            ],
        ),
    ]
