# Generated by Django 4.0.2 on 2022-05-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewup_app', '0006_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.IntegerField(db_column='qid', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='question')),
                ('answer', models.TextField(db_column='answer')),
                ('subdomain', models.CharField(db_column='subdomain', max_length=100)),
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='interviewup_app.domain')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
