# Generated by Django 4.0.2 on 2022-05-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewup_app', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesCompanies',
            fields=[
                ('rcid', models.IntegerField(db_column='rcid', primary_key=True, serialize=False)),
                ('roles', models.CharField(db_column='roles', max_length=150)),
                ('companies', models.TextField(db_column='companies')),
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='interviewup_app.domain')),
            ],
            options={
                'db_table': 'roles_companies',
            },
        ),
    ]
